# Generated by Django 6.0.4 on 2026-04-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='puce',
            field=models.IntegerField(null=True),
        ),
    ]
