# Generated by Django 6.0.4 on 2026-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0002_member_joined_date_member_puce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1000)),
                ('page_count', models.IntegerField(null=True)),
            ],
        ),
    ]
