# Generated by Django 6.0.4 on 2026-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
