# Generated by Django 6.0.4 on 2026-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0004_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eye_color', models.CharField(max_length=6)),
                ('coat_color', models.CharField(max_length=6)),
                ('horn_color', models.CharField(max_length=6)),
                ('belly_color', models.CharField(max_length=6)),
                ('mane_color', models.CharField(max_length=6)),
                ('puce_id', models.CharField(max_length=6)),
                ('species', models.CharField(max_length=30)),
            ],
        ),
    ]
