# Generated by Django 6.0.4 on 2026-05-11 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0005_pony'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='champ1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pony',
            name='champ2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pony',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pony',
            name='pony_history',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pony',
            name='belly_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='pony',
            name='coat_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='pony',
            name='eye_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='pony',
            name='horn_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='pony',
            name='mane_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='pony',
            name='puce_id',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='pony',
            name='species',
            field=models.CharField(choices=[('1', 'Licorne'), ('2', 'Poney rustique'), ('3', 'Poney de sport'), ('4', 'Nocturne'), ('5', 'Digitale')], default='1', max_length=30),
        ),
    ]
