# Generated by Django 6.0.4 on 2026-05-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponies', '0006_pony_champ1_pony_champ2_pony_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='biotope',
            field=models.ImageField(default=1, max_length=1, upload_to=None),
            preserve_default=False,
        ),
    ]
